"""add_task_project_relation

Revision ID: 09abe65541c6
Revises: dece4d278e22
Create Date: 2026-05-05 22:29:53.303649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09abe65541c6'
down_revision: Union[str, Sequence[str], None] = 'dece4d278e22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_task_project_id'), 'task', ['project_id'], unique=False)
    op.create_foreign_key(None, 'task', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_index(op.f('ix_task_project_id'), table_name='task')
    op.drop_column('task', 'project_id')
    # ### end Alembic commands ###
